### ISSUE TITLE
Patreon integration

### ISSUE THREAD

**Issue by whoisgina** [whoisgina/lucid#10]
`Patreon API integration to provide tiered access to content for users. This may be accomplished with OAuth and browser caching, or with user accounts within Craft CMS — the exact implementation requires research. `

**Comment by whoisgina** [comment]
From Dani:
```I have a 3 tiers of patrons that get different access to things:
$5/mo: 10 pages ahead in Avialae, 1 episode ahead in Impact Theory
$10/mo: 10 pages ahead in Avialae, 2 episodes ahead in Impact Theory, access to last year of NSFW comics
$15/mo: 10 pages ahead in Avialae, 2 episodes ahead in Impact Theory, access to last year of NSFW comics, access to patreon-only store, physical copies of books (this probably won’t have much to do with the website)

I think it would be easiest for me if I could assign each post or page to be public or whatever tier of patron access. Like I said, I’m not super sure how this works, so if there is a better way lmk.
```

**Comment by whoisgina** [comment]
So I'm talking to Patreon now, but I'm not sure how to access their reply and put it to use. I have some ideas about how to store this info and I'm wondering if I can store it in an HTTP session instead of a user account on the site. Here's a basic explanation of that:
https://stackoverflow.com/questions/10566988/what-is-the-correct-and-safe-secure-way-to-keep-a-user-logged-in-cookies-sessi

**Comment by whoisgina** [comment]
https://craftcms.com/docs/templating/craft.session
https://craftcms.stackexchange.com/questions/2423/can-you-save-a-variable-in-session
https://craftcms.com/classreference/services/HttpSessionService

**Comment by misslucid** [comment]
Extras section:

Maybe the best way to do this is to have three different sections to the extra tab. The extras tab could drop down to show NSFW Extras/Sketchbook/Illustrations

NSFW Extras are for $10+ patrons

Sketchbook is for $5+ patrons

and Illustrations would be public

I was hoping the nsfw extras would be navigated similar to how avialae is done. So each extra would be a "chapter" and  the pages would use the same navigation as avialae:
![websitemockup09](https://user-images.githubusercontent.com/31388606/31588709-7baae41c-b1bb-11e7-9da1-fc978d7b6cc6.jpg)
There should also probably be a landing page to list the PDFs and their summaries. (I can just link each section to jump to the right chapter)

The sketchbook section can just be a landing page where I can list PDFs to download. Those aren't as in high demand, so I'm not too concerned with navigation on them.

The public illustrations would be a landing page with icons of all the illustrations that can be clicked on to pop up a gallery to navigate through.

**Comment by misslucid** [comment]
Oh and the $14/$15+ a month patrons are 3 episodes ahead in impact theory. I think that was a typo from the original doc I sent you.
