### ISSUE TITLE
Navigation dropdowns are too tall

### ISSUE THREAD

**Issue by misslucid** [whoisgina/lucid#37]
Another nitpicky thing you're probably aware of, the height of the dropdown menus for chapter/page navigation on Avialae is too much. That or it's not centered height-wise. The height might be fine if it were centered.

**Comment by whoisgina** [comment]
https://stackoverflow.com/questions/570642/height-of-an-html-select-box-dropdown

**Comment by whoisgina** [comment]
The height of these open dropdown menu is set automatically by the browser as explained in the answer linked above. It looks like there may be a way to replace the `select` with a JS version — I'm trying a few things, but it may be a while!

**Comment by misslucid** [comment]
Oh, got it! It actually looks fine now--I think it was just off centered before which was throwing me off. I'll test it on different browsers though.

**Comment by whoisgina** [comment]
Yeah, I did style the chapter/page nav a bit. I would still like to limit this length though, which it looks like I can achieve by replacing with a jQuery dropdown without much trouble.

https://jqueryui.com/selectmenu/#default

This would also allow me to style it any way you'd like. Might leave this until after the softest launch.
